language: c
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - bar
      - moreutils
notifications:
  email: false
script:
  - mispipe "docker build ." bar > build.log || tail -c 2097152 build.log
